# Generated by Django 4.2.4 on 2023-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_navernewsarticle_naversearchresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubecomment',
            name='video',
        ),
        migrations.AddField(
            model_name='youtubecomment',
            name='video_id',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
        ),
    ]
