# Generated by Django 4.2.4 on 2023-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_youtubecomment_video_youtubecomment_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('video_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YoutubeComment',
        ),
    ]
