# Generated by Django 4.2.4 on 2023-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_rename_comment_youtubevideocomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideocomment',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
    ]
