# Generated by Django 4.2.4 on 2023-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_alter_youtubevideocomment_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='navernewsarticle',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='naversearchresult',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtubesearchresult',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtubevideocomment',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
