# Generated by Django 4.2.4 on 2023-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_navernewsarticle_task_id_naversearchresult_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ds', models.DateTimeField(null=True)),
                ('de', models.DateTimeField(null=True)),
                ('limit', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
